// data = [{}, {}, {}..] 이런 식으로 들어가있는 것.
let data = [
    {
      "_id": "61ad9e2b2ef3b724c2065425",
      "index": 0,
      "picture": "http://placehold.it/32x32",
      "age": 32,
      "eyeColor": "brown",
      "name": "Foley Thornton",
      "gender": "male",
      "company": "XTH",
      "email": "foleythornton@xth.com",
      "phone": "+1 (983) 585-3715",
      "address": "805 Bergen Avenue, Whitestone, Wyoming, 5441"
    },
    {
      "_id": "61ad9e2b54c835aa0ccc3df7",
      "index": 1,
      "picture": "http://placehold.it/32x32",
      "age": 33,
      "eyeColor": "blue",
      "name": "Dianna Valenzuela",
      "gender": "female",
      "company": "TROPOLIS",
      "email": "diannavalenzuela@tropolis.com",
      "phone": "+1 (841) 426-2977",
      "address": "403 Bliss Terrace, Santel, Arkansas, 9321"
    },
    {
      "_id": "61ad9e2b8ea9add78d58b6ec",
      "index": 2,
      "picture": "http://placehold.it/32x32",
      "age": 28,
      "eyeColor": "brown",
      "name": "Lidia Giles",
      "gender": "female",
      "company": "REALYSIS",
      "email": "lidiagiles@realysis.com",
      "phone": "+1 (911) 406-2983",
      "address": "126 Newkirk Avenue, Garberville, Washington, 1805"
    },
    {
      "_id": "61ad9e2bd5029b3cab49298e",
      "index": 3,
      "picture": "http://placehold.it/32x32",
      "age": 24,
      "eyeColor": "blue",
      "name": "Shana Fuller",
      "gender": "female",
      "company": "DIGIGENE",
      "email": "shanafuller@digigene.com",
      "phone": "+1 (913) 525-2291",
      "address": "651 Portland Avenue, Chaparrito, California, 4382"
    },
    {
      "_id": "61ad9e2b30d076969e03c7e6",
      "index": 4,
      "picture": "http://placehold.it/32x32",
      "age": 38,
      "eyeColor": "brown",
      "name": "Sherri Burns",
      "gender": "female",
      "company": "ZENOLUX",
      "email": "sherriburns@zenolux.com",
      "phone": "+1 (990) 553-3083",
      "address": "213 Maple Avenue, Belvoir, Ohio, 9869"
    },
    {
      "_id": "61ad9e2b37694b76beefd633",
      "index": 5,
      "picture": "http://placehold.it/32x32",
      "age": 40,
      "eyeColor": "brown",
      "name": "Lambert Dunlap",
      "gender": "male",
      "company": "COMTOURS",
      "email": "lambertdunlap@comtours.com",
      "phone": "+1 (976) 555-2547",
      "address": "230 Lenox Road, Greensburg, South Dakota, 3536"
    },
    {
      "_id": "61ad9e2be6465575f1448005",
      "index": 6,
      "picture": "http://placehold.it/32x32",
      "age": 31,
      "eyeColor": "blue",
      "name": "Velazquez Mcgowan",
      "gender": "male",
      "company": "QABOOS",
      "email": "velazquezmcgowan@qaboos.com",
      "phone": "+1 (851) 484-3580",
      "address": "289 Bevy Court, Clarence, Iowa, 9237"
    },
    {
      "_id": "61ad9e2bf20766cb73b03998",
      "index": 7,
      "picture": "http://placehold.it/32x32",
      "age": 39,
      "eyeColor": "brown",
      "name": "Delaney Valencia",
      "gender": "male",
      "company": "ENDIPIN",
      "email": "delaneyvalencia@endipin.com",
      "phone": "+1 (927) 588-2005",
      "address": "270 Vandervoort Avenue, Hannasville, American Samoa, 6498"
    },
    {
      "_id": "61ad9e2bb8cde2ec9d88a0c9",
      "index": 8,
      "picture": "http://placehold.it/32x32",
      "age": 39,
      "eyeColor": "brown",
      "name": "Cochran Strickland",
      "gender": "male",
      "company": "SUPPORTAL",
      "email": "cochranstrickland@supportal.com",
      "phone": "+1 (961) 419-2668",
      "address": "752 Dekalb Avenue, Ellerslie, Northern Mariana Islands, 3972"
    }
  ]